name: Continuous Integration

permissions:
  pull-requests: write

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    uses: ./.github/workflows/test.yml
    secrets: inherit
  
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    needs: test
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: "actions/checkout@v3"
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: "commitizen-tools/commitizen-action@master"
        with:
          github_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
