name: Run Tests

permissions:
  pull-requests: write

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with ruff
      uses: chartboost/ruff-action@v1
    - name: Test with pytest
      run: |
        poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov="snekoil" | tee pytest-coverage.txt
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        badge-title: "Test Coverage"
